services:
  - type: web
    name: chatgpt-scraper
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production